# Generated by Django 3.2.18 on 2023-04-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuser',
            name='steam_url',
            field=models.URLField(default=None),
        ),
    ]
