# Generated by Django 3.2.18 on 2023-04-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_tradeuser_steam_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeuser',
            name='steam_url',
            field=models.CharField(default='17자리 숫자를 입력해 주세요', max_length=17),
        ),
    ]
